#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCALERANGE 10
#define UNITREPHEIGHT 40
#define DEFAULTTASKHEIGHT 10
#define SCROLLAMOUNT 20
#define UNITNAMEBARWIDTH 40
#define XMLCONFIGFILE "config.xml"

#endif // CONSTANTS_H
