#############################################################################
# Makefile for building: Gantt.app/Contents/MacOS/Gantt
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Gantt.pro
# Template: app
# Command: /Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gantt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib
QMAKE         = /Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Gantt1.0.0
DISTDIR = /Users/juliusnaeumann/Developer/Gantt/.tmp/Gantt1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		ganttrect.cpp \
		ganttflow.cpp \
		qtablewidgetnumberitem.cpp \
		gclgms.c \
		gdxcc.c \
		wizard.cpp \
		exportwizard.cpp moc_mainwindow.cpp \
		moc_ganttrect.cpp \
		moc_ganttflow.cpp \
		moc_wizard.cpp \
		moc_exportwizard.cpp
OBJECTS       = main.o \
		mainwindow.o \
		ganttrect.o \
		ganttflow.o \
		qtablewidgetnumberitem.o \
		gclgms.o \
		gdxcc.o \
		wizard.o \
		exportwizard.o \
		moc_mainwindow.o \
		moc_ganttrect.o \
		moc_ganttflow.o \
		moc_wizard.o \
		moc_exportwizard.o
DIST          = gantticon.png \
		gantticon.ico \
		icon.icns \
		gantt.rc \
		../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gantt.pro mainwindow.h \
		ganttrect.h \
		ganttflow.h \
		constants.h \
		qtablewidgetnumberitem.h \
		gclgms.h \
		gdxcc.h \
		wizard.h \
		exportwizard.h main.cpp \
		mainwindow.cpp \
		ganttrect.cpp \
		ganttflow.cpp \
		qtablewidgetnumberitem.cpp \
		gclgms.c \
		gdxcc.c \
		wizard.cpp \
		exportwizard.cpp
QMAKE_TARGET  = Gantt
DESTDIR       = 
TARGET        = Gantt.app/Contents/MacOS/Gantt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_wizard.h ui_exportwizard.h $(OBJECTS)  
	@test -d Gantt.app/Contents/MacOS/ || mkdir -p Gantt.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gantt.pro ../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gantt.pro \
		../Qt/5.7/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gantt.pro
../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Gantt.pro:
../Qt/5.7/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Gantt.pro

qmake_all: FORCE

Gantt.app/Contents/PkgInfo: 
	@test -d Gantt.app/Contents || mkdir -p Gantt.app/Contents
	@$(DEL_FILE) Gantt.app/Contents/PkgInfo
	@echo "APPL????" > Gantt.app/Contents/PkgInfo
Gantt.app/Contents/Resources/empty.lproj: 
	@test -d Gantt.app/Contents/Resources || mkdir -p Gantt.app/Contents/Resources
	@touch Gantt.app/Contents/Resources/empty.lproj
	
Gantt.app/Contents/Info.plist: 
	@test -d Gantt.app/Contents || mkdir -p Gantt.app/Contents
	@$(DEL_FILE) Gantt.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.coolius.Gantt,g" -e "s,@ICON@,icon.icns,g" -e "s,@EXECUTABLE@,Gantt,g" -e "s,@LIBRARY@,Gantt,g" -e "s,@TYPEINFO@,????,g" ../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Gantt.app/Contents/Info.plist
Gantt.app/Contents/Resources/icon.icns: icon.icns
	@test -d Gantt.app/Contents/Resources/ || mkdir -p Gantt.app/Contents/Resources/
	@$(DEL_FILE) Gantt.app/Contents/Resources/icon.icns
	@$(COPY_FILE) icon.icns Gantt.app/Contents/Resources/icon.icns

all: Makefile \
		Gantt.app/Contents/PkgInfo \
		Gantt.app/Contents/Resources/empty.lproj \
		Gantt.app/Contents/Info.plist \
		Gantt.app/Contents/Resources/icon.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h ganttrect.h ganttflow.h constants.h qtablewidgetnumberitem.h gclgms.h gdxcc.h wizard.h exportwizard.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp ganttrect.cpp ganttflow.cpp qtablewidgetnumberitem.cpp gclgms.c gdxcc.c wizard.cpp exportwizard.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui wizard.ui exportwizard.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Gantt.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_ganttrect.cpp moc_ganttflow.cpp moc_wizard.cpp moc_exportwizard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_ganttrect.cpp moc_ganttflow.cpp moc_wizard.cpp moc_exportwizard.cpp
moc_mainwindow.cpp: ../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		mainwindow.h \
		mainwindow.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_ganttrect.cpp: ../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib ganttrect.h -o moc_ganttrect.cpp

moc_ganttflow.cpp: ../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttflow.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib ganttflow.h -o moc_ganttflow.cpp

moc_wizard.cpp: ../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		wizard.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib wizard.h -o moc_wizard.cpp

moc_exportwizard.cpp: ../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		exportwizard.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib exportwizard.h -o moc_exportwizard.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_wizard.h ui_exportwizard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_wizard.h ui_exportwizard.h
ui_mainwindow.h: mainwindow.ui \
		../Qt/5.7/clang_64/bin/uic
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_wizard.h: wizard.ui \
		../Qt/5.7/clang_64/bin/uic
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/uic wizard.ui -o ui_wizard.h

ui_exportwizard.h: exportwizard.ui \
		../Qt/5.7/clang_64/bin/uic
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/uic exportwizard.ui -o ui_exportwizard.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		ui_mainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QtMath \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QToolTip \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		constants.h \
		qtablewidgetnumberitem.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers/QPrinter \
		../Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers/qprinter.h \
		exportwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ganttrect.o: ganttrect.cpp ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		constants.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QtGui \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVariantAnimation \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvariantanimation.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttrect.o ganttrect.cpp

ganttflow.o: ganttflow.cpp ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttflow.o ganttflow.cpp

qtablewidgetnumberitem.o: qtablewidgetnumberitem.cpp qtablewidgetnumberitem.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtablewidgetnumberitem.o qtablewidgetnumberitem.cpp

gclgms.o: gclgms.c gclgms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gclgms.o gclgms.c

gdxcc.o: gdxcc.c gdxcc.h \
		gclgms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gdxcc.o gdxcc.c

wizard.o: wizard.cpp wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		ui_wizard.h \
		gclgms.h \
		gdxcc.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizard.o wizard.cpp

exportwizard.o: exportwizard.cpp exportwizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		ui_exportwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportwizard.o exportwizard.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ganttrect.o: moc_ganttrect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganttrect.o moc_ganttrect.cpp

moc_ganttflow.o: moc_ganttflow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganttflow.o moc_ganttflow.cpp

moc_wizard.o: moc_wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizard.o moc_wizard.cpp

moc_exportwizard.o: moc_exportwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportwizard.o moc_exportwizard.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

