#############################################################################
# Makefile for building: Gantt.app/Contents/MacOS/Gantt
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Gantt.pro
# Template: app
# Command: /Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile Gantt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib
QMAKE         = /Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Gantt1.0.0
DISTDIR = /Users/juliusnaeumann/Developer/Gantt/.tmp/Gantt1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		ganttrect.cpp \
		ganttflow.cpp \
		qtablewidgetnumberitem.cpp \
		gclgms.c \
		gdxcc.c \
		wizard.cpp \
		exportwizard.cpp \
		ganttgraphicsview.cpp \
		ganttline.cpp qrc_icons.cpp \
		moc_mainwindow.cpp \
		moc_ganttrect.cpp \
		moc_ganttflow.cpp \
		moc_wizard.cpp \
		moc_exportwizard.cpp \
		moc_ganttline.cpp
OBJECTS       = main.o \
		mainwindow.o \
		ganttrect.o \
		ganttflow.o \
		qtablewidgetnumberitem.o \
		gclgms.o \
		gdxcc.o \
		wizard.o \
		exportwizard.o \
		ganttgraphicsview.o \
		ganttline.o \
		qrc_icons.o \
		moc_mainwindow.o \
		moc_ganttrect.o \
		moc_ganttflow.o \
		moc_wizard.o \
		moc_exportwizard.o \
		moc_ganttline.o
DIST          = gantticon.png \
		gantticon.ico \
		icon.icns \
		ionicons-2.0.1/png/512/alert-circled.png \
		ionicons-2.0.1/png/512/alert.png \
		ionicons-2.0.1/png/512/android-add-contact.png \
		ionicons-2.0.1/png/512/android-add.png \
		ionicons-2.0.1/png/512/android-alarm.png \
		ionicons-2.0.1/png/512/android-archive.png \
		ionicons-2.0.1/png/512/android-arrow-back.png \
		ionicons-2.0.1/png/512/android-arrow-down-left.png \
		ionicons-2.0.1/png/512/android-arrow-down-right.png \
		ionicons-2.0.1/png/512/android-arrow-forward.png \
		ionicons-2.0.1/png/512/android-arrow-up-left.png \
		ionicons-2.0.1/png/512/android-arrow-up-right.png \
		ionicons-2.0.1/png/512/android-battery.png \
		ionicons-2.0.1/png/512/android-book.png \
		ionicons-2.0.1/png/512/android-calendar.png \
		ionicons-2.0.1/png/512/android-call.png \
		ionicons-2.0.1/png/512/android-camera.png \
		ionicons-2.0.1/png/512/android-chat.png \
		ionicons-2.0.1/png/512/android-checkmark.png \
		ionicons-2.0.1/png/512/android-clock.png \
		ionicons-2.0.1/png/512/android-close.png \
		ionicons-2.0.1/png/512/android-contact.png \
		ionicons-2.0.1/png/512/android-contacts.png \
		ionicons-2.0.1/png/512/android-data.png \
		ionicons-2.0.1/png/512/android-developer.png \
		ionicons-2.0.1/png/512/android-display.png \
		ionicons-2.0.1/png/512/android-download.png \
		ionicons-2.0.1/png/512/android-drawer.png \
		ionicons-2.0.1/png/512/android-dropdown.png \
		ionicons-2.0.1/png/512/android-earth.png \
		ionicons-2.0.1/png/512/android-folder.png \
		ionicons-2.0.1/png/512/android-forums.png \
		ionicons-2.0.1/png/512/android-friends.png \
		ionicons-2.0.1/png/512/android-hand.png \
		ionicons-2.0.1/png/512/android-image.png \
		ionicons-2.0.1/png/512/android-inbox.png \
		ionicons-2.0.1/png/512/android-information.png \
		ionicons-2.0.1/png/512/android-keypad.png \
		ionicons-2.0.1/png/512/android-lightbulb.png \
		ionicons-2.0.1/png/512/android-locate.png \
		ionicons-2.0.1/png/512/android-location.png \
		ionicons-2.0.1/png/512/android-mail.png \
		ionicons-2.0.1/png/512/android-microphone.png \
		ionicons-2.0.1/png/512/android-mixer.png \
		ionicons-2.0.1/png/512/android-more.png \
		ionicons-2.0.1/png/512/android-note.png \
		ionicons-2.0.1/png/512/android-playstore.png \
		ionicons-2.0.1/png/512/android-printer.png \
		ionicons-2.0.1/png/512/android-promotion.png \
		ionicons-2.0.1/png/512/android-reminder.png \
		ionicons-2.0.1/png/512/android-remove.png \
		ionicons-2.0.1/png/512/android-search.png \
		ionicons-2.0.1/png/512/android-send.png \
		ionicons-2.0.1/png/512/android-settings.png \
		ionicons-2.0.1/png/512/android-share.png \
		ionicons-2.0.1/png/512/android-social-user.png \
		ionicons-2.0.1/png/512/android-social.png \
		ionicons-2.0.1/png/512/android-sort.png \
		ionicons-2.0.1/png/512/android-stair-drawer.png \
		ionicons-2.0.1/png/512/android-star.png \
		ionicons-2.0.1/png/512/android-stopwatch.png \
		ionicons-2.0.1/png/512/android-storage.png \
		ionicons-2.0.1/png/512/android-system-back.png \
		ionicons-2.0.1/png/512/android-system-home.png \
		ionicons-2.0.1/png/512/android-system-windows.png \
		ionicons-2.0.1/png/512/android-timer.png \
		ionicons-2.0.1/png/512/android-trash.png \
		ionicons-2.0.1/png/512/android-user-menu.png \
		ionicons-2.0.1/png/512/android-volume.png \
		ionicons-2.0.1/png/512/android-wifi.png \
		ionicons-2.0.1/png/512/aperture.png \
		ionicons-2.0.1/png/512/archive.png \
		ionicons-2.0.1/png/512/arrow-down-a.png \
		ionicons-2.0.1/png/512/arrow-down-b.png \
		ionicons-2.0.1/png/512/arrow-down-c.png \
		ionicons-2.0.1/png/512/arrow-expand.png \
		ionicons-2.0.1/png/512/arrow-graph-down-left.png \
		ionicons-2.0.1/png/512/arrow-graph-down-right.png \
		ionicons-2.0.1/png/512/arrow-graph-up-left.png \
		ionicons-2.0.1/png/512/arrow-graph-up-right.png \
		ionicons-2.0.1/png/512/arrow-left-a.png \
		ionicons-2.0.1/png/512/arrow-left-b.png \
		ionicons-2.0.1/png/512/arrow-left-c.png \
		ionicons-2.0.1/png/512/arrow-move.png \
		ionicons-2.0.1/png/512/arrow-resize.png \
		ionicons-2.0.1/png/512/arrow-return-left.png \
		ionicons-2.0.1/png/512/arrow-return-right.png \
		ionicons-2.0.1/png/512/arrow-right-a.png \
		ionicons-2.0.1/png/512/arrow-right-b.png \
		ionicons-2.0.1/png/512/arrow-right-c.png \
		ionicons-2.0.1/png/512/arrow-shrink.png \
		ionicons-2.0.1/png/512/arrow-swap.png \
		ionicons-2.0.1/png/512/arrow-up-a.png \
		ionicons-2.0.1/png/512/arrow-up-b.png \
		ionicons-2.0.1/png/512/arrow-up-c.png \
		ionicons-2.0.1/png/512/asterisk.png \
		ionicons-2.0.1/png/512/at.png \
		ionicons-2.0.1/png/512/bag.png \
		ionicons-2.0.1/png/512/battery-charging.png \
		ionicons-2.0.1/png/512/battery-empty.png \
		ionicons-2.0.1/png/512/battery-full.png \
		ionicons-2.0.1/png/512/battery-half.png \
		ionicons-2.0.1/png/512/battery-low.png \
		ionicons-2.0.1/png/512/beaker.png \
		ionicons-2.0.1/png/512/beer.png \
		ionicons-2.0.1/png/512/bluetooth.png \
		ionicons-2.0.1/png/512/bonfire.png \
		ionicons-2.0.1/png/512/bookmark.png \
		ionicons-2.0.1/png/512/briefcase.png \
		ionicons-2.0.1/png/512/bug.png \
		ionicons-2.0.1/png/512/calculator.png \
		ionicons-2.0.1/png/512/calendar.png \
		ionicons-2.0.1/png/512/camera.png \
		ionicons-2.0.1/png/512/card.png \
		ionicons-2.0.1/png/512/cash.png \
		ionicons-2.0.1/png/512/chatbox-working.png \
		ionicons-2.0.1/png/512/chatbox.png \
		ionicons-2.0.1/png/512/chatboxes.png \
		ionicons-2.0.1/png/512/chatbubble-working.png \
		ionicons-2.0.1/png/512/chatbubble.png \
		ionicons-2.0.1/png/512/chatbubbles.png \
		ionicons-2.0.1/png/512/checkmark-circled.png \
		ionicons-2.0.1/png/512/checkmark-round.png \
		ionicons-2.0.1/png/512/checkmark.png \
		ionicons-2.0.1/png/512/chevron-down.png \
		ionicons-2.0.1/png/512/chevron-left.png \
		ionicons-2.0.1/png/512/chevron-right.png \
		ionicons-2.0.1/png/512/chevron-up.png \
		ionicons-2.0.1/png/512/clipboard.png \
		ionicons-2.0.1/png/512/clock.png \
		ionicons-2.0.1/png/512/close-circled.png \
		ionicons-2.0.1/png/512/close-round.png \
		ionicons-2.0.1/png/512/close.png \
		ionicons-2.0.1/png/512/closed-captioning.png \
		ionicons-2.0.1/png/512/cloud.png \
		ionicons-2.0.1/png/512/code-download.png \
		ionicons-2.0.1/png/512/code-working.png \
		ionicons-2.0.1/png/512/code.png \
		ionicons-2.0.1/png/512/coffee.png \
		ionicons-2.0.1/png/512/compass.png \
		ionicons-2.0.1/png/512/compose.png \
		ionicons-2.0.1/png/512/connection-bars.png \
		ionicons-2.0.1/png/512/contrast.png \
		ionicons-2.0.1/png/512/cube.png \
		ionicons-2.0.1/png/512/disc.png \
		ionicons-2.0.1/png/512/document-text.png \
		ionicons-2.0.1/png/512/document.png \
		ionicons-2.0.1/png/512/drag.png \
		ionicons-2.0.1/png/512/earth.png \
		ionicons-2.0.1/png/512/edit.png \
		ionicons-2.0.1/png/512/egg.png \
		ionicons-2.0.1/png/512/eject.png \
		ionicons-2.0.1/png/512/email.png \
		ionicons-2.0.1/png/512/eye-disabled.png \
		ionicons-2.0.1/png/512/eye.png \
		ionicons-2.0.1/png/512/female.png \
		ionicons-2.0.1/png/512/filing.png \
		ionicons-2.0.1/png/512/film-marker.png \
		ionicons-2.0.1/png/512/fireball.png \
		ionicons-2.0.1/png/512/flag.png \
		ionicons-2.0.1/png/512/flame.png \
		ionicons-2.0.1/png/512/flash-off.png \
		ionicons-2.0.1/png/512/flash.png \
		ionicons-2.0.1/png/512/flask.png \
		ionicons-2.0.1/png/512/folder.png \
		ionicons-2.0.1/png/512/fork-repo.png \
		ionicons-2.0.1/png/512/fork.png \
		ionicons-2.0.1/png/512/forward.png \
		ionicons-2.0.1/png/512/funnel.png \
		ionicons-2.0.1/png/512/game-controller-a.png \
		ionicons-2.0.1/png/512/game-controller-b.png \
		ionicons-2.0.1/png/512/gear-a.png \
		ionicons-2.0.1/png/512/gear-b.png \
		ionicons-2.0.1/png/512/grid.png \
		ionicons-2.0.1/png/512/hammer.png \
		ionicons-2.0.1/png/512/happy.png \
		ionicons-2.0.1/png/512/headphone.png \
		ionicons-2.0.1/png/512/heart-broken.png \
		ionicons-2.0.1/png/512/heart.png \
		ionicons-2.0.1/png/512/help-buoy.png \
		ionicons-2.0.1/png/512/help-circled.png \
		ionicons-2.0.1/png/512/help.png \
		ionicons-2.0.1/png/512/home.png \
		ionicons-2.0.1/png/512/icecream.png \
		ionicons-2.0.1/png/512/icon-social-google-plus-outline.png \
		ionicons-2.0.1/png/512/icon-social-google-plus.png \
		ionicons-2.0.1/png/512/image.png \
		ionicons-2.0.1/png/512/images.png \
		ionicons-2.0.1/png/512/information-circled.png \
		ionicons-2.0.1/png/512/information.png \
		ionicons-2.0.1/png/512/ionic.png \
		ionicons-2.0.1/png/512/ios7-alarm-outline.png \
		ionicons-2.0.1/png/512/ios7-alarm.png \
		ionicons-2.0.1/png/512/ios7-albums-outline.png \
		ionicons-2.0.1/png/512/ios7-albums.png \
		ionicons-2.0.1/png/512/ios7-americanfootball-outline.png \
		ionicons-2.0.1/png/512/ios7-americanfootball.png \
		ionicons-2.0.1/png/512/ios7-analytics-outline.png \
		ionicons-2.0.1/png/512/ios7-analytics.png \
		ionicons-2.0.1/png/512/ios7-arrow-back.png \
		ionicons-2.0.1/png/512/ios7-arrow-down.png \
		ionicons-2.0.1/png/512/ios7-arrow-forward.png \
		ionicons-2.0.1/png/512/ios7-arrow-left.png \
		ionicons-2.0.1/png/512/ios7-arrow-right.png \
		ionicons-2.0.1/png/512/ios7-arrow-thin-down.png \
		ionicons-2.0.1/png/512/ios7-arrow-thin-left.png \
		ionicons-2.0.1/png/512/ios7-arrow-thin-right.png \
		ionicons-2.0.1/png/512/ios7-arrow-thin-up.png \
		ionicons-2.0.1/png/512/ios7-arrow-up.png \
		ionicons-2.0.1/png/512/ios7-at-outline.png \
		ionicons-2.0.1/png/512/ios7-at.png \
		ionicons-2.0.1/png/512/ios7-barcode-outline.png \
		ionicons-2.0.1/png/512/ios7-barcode.png \
		ionicons-2.0.1/png/512/ios7-baseball-outline.png \
		ionicons-2.0.1/png/512/ios7-baseball.png \
		ionicons-2.0.1/png/512/ios7-basketball-outline.png \
		ionicons-2.0.1/png/512/ios7-basketball.png \
		ionicons-2.0.1/png/512/ios7-bell-outline.png \
		ionicons-2.0.1/png/512/ios7-bell.png \
		ionicons-2.0.1/png/512/ios7-bolt-outline.png \
		ionicons-2.0.1/png/512/ios7-bolt.png \
		ionicons-2.0.1/png/512/ios7-bookmarks-outline.png \
		ionicons-2.0.1/png/512/ios7-bookmarks.png \
		ionicons-2.0.1/png/512/ios7-box-outline.png \
		ionicons-2.0.1/png/512/ios7-box.png \
		ionicons-2.0.1/png/512/ios7-briefcase-outline.png \
		ionicons-2.0.1/png/512/ios7-briefcase.png \
		ionicons-2.0.1/png/512/ios7-browsers-outline.png \
		ionicons-2.0.1/png/512/ios7-browsers.png \
		ionicons-2.0.1/png/512/ios7-calculator-outline.png \
		ionicons-2.0.1/png/512/ios7-calculator.png \
		ionicons-2.0.1/png/512/ios7-calendar-outline.png \
		ionicons-2.0.1/png/512/ios7-calendar.png \
		ionicons-2.0.1/png/512/ios7-camera-outline.png \
		ionicons-2.0.1/png/512/ios7-camera.png \
		ionicons-2.0.1/png/512/ios7-cart-outline.png \
		ionicons-2.0.1/png/512/ios7-cart.png \
		ionicons-2.0.1/png/512/ios7-chatboxes-outline.png \
		ionicons-2.0.1/png/512/ios7-chatboxes.png \
		ionicons-2.0.1/png/512/ios7-chatbubble-outline.png \
		ionicons-2.0.1/png/512/ios7-chatbubble.png \
		ionicons-2.0.1/png/512/ios7-checkmark-empty.png \
		ionicons-2.0.1/png/512/ios7-checkmark-outline.png \
		ionicons-2.0.1/png/512/ios7-checkmark.png \
		ionicons-2.0.1/png/512/ios7-circle-filled.png \
		ionicons-2.0.1/png/512/ios7-circle-outline.png \
		ionicons-2.0.1/png/512/ios7-clock-outline.png \
		ionicons-2.0.1/png/512/ios7-clock.png \
		ionicons-2.0.1/png/512/ios7-close-empty.png \
		ionicons-2.0.1/png/512/ios7-close-outline.png \
		ionicons-2.0.1/png/512/ios7-close.png \
		ionicons-2.0.1/png/512/ios7-cloud-download-outline.png \
		ionicons-2.0.1/png/512/ios7-cloud-download.png \
		ionicons-2.0.1/png/512/ios7-cloud-outline.png \
		ionicons-2.0.1/png/512/ios7-cloud-upload-outline.png \
		ionicons-2.0.1/png/512/ios7-cloud-upload.png \
		ionicons-2.0.1/png/512/ios7-cloud.png \
		ionicons-2.0.1/png/512/ios7-cloudy-night-outline.png \
		ionicons-2.0.1/png/512/ios7-cloudy-night.png \
		ionicons-2.0.1/png/512/ios7-cloudy-outline.png \
		ionicons-2.0.1/png/512/ios7-cloudy.png \
		ionicons-2.0.1/png/512/ios7-cog-outline.png \
		ionicons-2.0.1/png/512/ios7-cog.png \
		ionicons-2.0.1/png/512/ios7-compose-outline.png \
		ionicons-2.0.1/png/512/ios7-compose.png \
		ionicons-2.0.1/png/512/ios7-contact-outline.png \
		ionicons-2.0.1/png/512/ios7-contact.png \
		ionicons-2.0.1/png/512/ios7-copy-outline.png \
		ionicons-2.0.1/png/512/ios7-copy.png \
		ionicons-2.0.1/png/512/ios7-download-outline.png \
		ionicons-2.0.1/png/512/ios7-download.png \
		ionicons-2.0.1/png/512/ios7-drag.png \
		ionicons-2.0.1/png/512/ios7-email-outline.png \
		ionicons-2.0.1/png/512/ios7-email.png \
		ionicons-2.0.1/png/512/ios7-expand.png \
		ionicons-2.0.1/png/512/ios7-eye-outline.png \
		ionicons-2.0.1/png/512/ios7-eye.png \
		ionicons-2.0.1/png/512/ios7-fastforward-outline.png \
		ionicons-2.0.1/png/512/ios7-fastforward.png \
		ionicons-2.0.1/png/512/ios7-filing-outline.png \
		ionicons-2.0.1/png/512/ios7-filing.png \
		ionicons-2.0.1/png/512/ios7-film-outline.png \
		ionicons-2.0.1/png/512/ios7-film.png \
		ionicons-2.0.1/png/512/ios7-flag-outline.png \
		ionicons-2.0.1/png/512/ios7-flag.png \
		ionicons-2.0.1/png/512/ios7-folder-outline.png \
		ionicons-2.0.1/png/512/ios7-folder.png \
		ionicons-2.0.1/png/512/ios7-football-outline.png \
		ionicons-2.0.1/png/512/ios7-football.png \
		ionicons-2.0.1/png/512/ios7-gear-outline.png \
		ionicons-2.0.1/png/512/ios7-gear.png \
		ionicons-2.0.1/png/512/ios7-glasses-outline.png \
		ionicons-2.0.1/png/512/ios7-glasses.png \
		ionicons-2.0.1/png/512/ios7-heart-outline.png \
		ionicons-2.0.1/png/512/ios7-heart.png \
		ionicons-2.0.1/png/512/ios7-help-empty.png \
		ionicons-2.0.1/png/512/ios7-help-outline.png \
		ionicons-2.0.1/png/512/ios7-help.png \
		ionicons-2.0.1/png/512/ios7-home-outline.png \
		ionicons-2.0.1/png/512/ios7-home.png \
		ionicons-2.0.1/png/512/ios7-infinite-outline.png \
		ionicons-2.0.1/png/512/ios7-infinite.png \
		ionicons-2.0.1/png/512/ios7-information-empty.png \
		ionicons-2.0.1/png/512/ios7-information-outline.png \
		ionicons-2.0.1/png/512/ios7-information.png \
		ionicons-2.0.1/png/512/ios7-ionic-outline.png \
		ionicons-2.0.1/png/512/ios7-keypad-outline.png \
		ionicons-2.0.1/png/512/ios7-keypad.png \
		ionicons-2.0.1/png/512/ios7-lightbulb-outline.png \
		ionicons-2.0.1/png/512/ios7-lightbulb.png \
		ionicons-2.0.1/png/512/ios7-location-outline.png \
		ionicons-2.0.1/png/512/ios7-location.png \
		ionicons-2.0.1/png/512/ios7-locked-outline.png \
		ionicons-2.0.1/png/512/ios7-locked.png \
		ionicons-2.0.1/png/512/ios7-loop-strong.png \
		ionicons-2.0.1/png/512/ios7-loop.png \
		ionicons-2.0.1/png/512/ios7-medkit-outline.png \
		ionicons-2.0.1/png/512/ios7-medkit.png \
		ionicons-2.0.1/png/512/ios7-mic-off.png \
		ionicons-2.0.1/png/512/ios7-mic-outline.png \
		ionicons-2.0.1/png/512/ios7-mic.png \
		ionicons-2.0.1/png/512/ios7-minus-empty.png \
		ionicons-2.0.1/png/512/ios7-minus-outline.png \
		ionicons-2.0.1/png/512/ios7-minus.png \
		ionicons-2.0.1/png/512/ios7-monitor-outline.png \
		ionicons-2.0.1/png/512/ios7-monitor.png \
		ionicons-2.0.1/png/512/ios7-moon-outline.png \
		ionicons-2.0.1/png/512/ios7-moon.png \
		ionicons-2.0.1/png/512/ios7-more-outline.png \
		ionicons-2.0.1/png/512/ios7-more.png \
		ionicons-2.0.1/png/512/ios7-musical-note.png \
		ionicons-2.0.1/png/512/ios7-musical-notes.png \
		ionicons-2.0.1/png/512/ios7-navigate-outline.png \
		ionicons-2.0.1/png/512/ios7-navigate.png \
		ionicons-2.0.1/png/512/ios7-paper-outline.png \
		ionicons-2.0.1/png/512/ios7-paper.png \
		ionicons-2.0.1/png/512/ios7-paperplane-outline.png \
		ionicons-2.0.1/png/512/ios7-paperplane.png \
		ionicons-2.0.1/png/512/ios7-partlysunny-outline.png \
		ionicons-2.0.1/png/512/ios7-partlysunny.png \
		ionicons-2.0.1/png/512/ios7-pause-outline.png \
		ionicons-2.0.1/png/512/ios7-pause.png \
		ionicons-2.0.1/png/512/ios7-paw-outline.png \
		ionicons-2.0.1/png/512/ios7-paw.png \
		ionicons-2.0.1/png/512/ios7-people-outline.png \
		ionicons-2.0.1/png/512/ios7-people.png \
		ionicons-2.0.1/png/512/ios7-person-outline.png \
		ionicons-2.0.1/png/512/ios7-person.png \
		ionicons-2.0.1/png/512/ios7-personadd-outline.png \
		ionicons-2.0.1/png/512/ios7-personadd.png \
		ionicons-2.0.1/png/512/ios7-photos-outline.png \
		ionicons-2.0.1/png/512/ios7-photos.png \
		ionicons-2.0.1/png/512/ios7-pie-outline.png \
		ionicons-2.0.1/png/512/ios7-pie.png \
		ionicons-2.0.1/png/512/ios7-play-outline.png \
		ionicons-2.0.1/png/512/ios7-play.png \
		ionicons-2.0.1/png/512/ios7-plus-empty.png \
		ionicons-2.0.1/png/512/ios7-plus-outline.png \
		ionicons-2.0.1/png/512/ios7-plus.png \
		ionicons-2.0.1/png/512/ios7-pricetag-outline.png \
		ionicons-2.0.1/png/512/ios7-pricetag.png \
		ionicons-2.0.1/png/512/ios7-pricetags-outline.png \
		ionicons-2.0.1/png/512/ios7-pricetags.png \
		ionicons-2.0.1/png/512/ios7-printer-outline.png \
		ionicons-2.0.1/png/512/ios7-printer.png \
		ionicons-2.0.1/png/512/ios7-pulse-strong.png \
		ionicons-2.0.1/png/512/ios7-pulse.png \
		ionicons-2.0.1/png/512/ios7-rainy-outline.png \
		ionicons-2.0.1/png/512/ios7-rainy.png \
		ionicons-2.0.1/png/512/ios7-recording-outline.png \
		ionicons-2.0.1/png/512/ios7-recording.png \
		ionicons-2.0.1/png/512/ios7-redo-outline.png \
		ionicons-2.0.1/png/512/ios7-redo.png \
		ionicons-2.0.1/png/512/ios7-refresh-empty.png \
		ionicons-2.0.1/png/512/ios7-refresh-outline.png \
		ionicons-2.0.1/png/512/ios7-refresh.png \
		ionicons-2.0.1/png/512/ios7-reload.png \
		ionicons-2.0.1/png/512/ios7-reverse-camera-outline.png \
		ionicons-2.0.1/png/512/ios7-reverse-camera.png \
		ionicons-2.0.1/png/512/ios7-rewind-outline.png \
		ionicons-2.0.1/png/512/ios7-rewind.png \
		ionicons-2.0.1/png/512/ios7-search-strong.png \
		ionicons-2.0.1/png/512/ios7-search.png \
		ionicons-2.0.1/png/512/ios7-settings-strong.png \
		ionicons-2.0.1/png/512/ios7-settings.png \
		ionicons-2.0.1/png/512/ios7-shrink.png \
		ionicons-2.0.1/png/512/ios7-skipbackward-outline.png \
		ionicons-2.0.1/png/512/ios7-skipbackward.png \
		ionicons-2.0.1/png/512/ios7-skipforward-outline.png \
		ionicons-2.0.1/png/512/ios7-skipforward.png \
		ionicons-2.0.1/png/512/ios7-snowy.png \
		ionicons-2.0.1/png/512/ios7-speedometer-outline.png \
		ionicons-2.0.1/png/512/ios7-speedometer.png \
		ionicons-2.0.1/png/512/ios7-star-half.png \
		ionicons-2.0.1/png/512/ios7-star-outline.png \
		ionicons-2.0.1/png/512/ios7-star.png \
		ionicons-2.0.1/png/512/ios7-stopwatch-outline.png \
		ionicons-2.0.1/png/512/ios7-stopwatch.png \
		ionicons-2.0.1/png/512/ios7-sunny-outline.png \
		ionicons-2.0.1/png/512/ios7-sunny.png \
		ionicons-2.0.1/png/512/ios7-telephone-outline.png \
		ionicons-2.0.1/png/512/ios7-telephone.png \
		ionicons-2.0.1/png/512/ios7-tennisball-outline.png \
		ionicons-2.0.1/png/512/ios7-tennisball.png \
		ionicons-2.0.1/png/512/ios7-thunderstorm-outline.png \
		ionicons-2.0.1/png/512/ios7-thunderstorm.png \
		ionicons-2.0.1/png/512/ios7-time-outline.png \
		ionicons-2.0.1/png/512/ios7-time.png \
		ionicons-2.0.1/png/512/ios7-timer-outline.png \
		ionicons-2.0.1/png/512/ios7-timer.png \
		ionicons-2.0.1/png/512/ios7-toggle-outline.png \
		ionicons-2.0.1/png/512/ios7-toggle.png \
		ionicons-2.0.1/png/512/ios7-trash-outline.png \
		ionicons-2.0.1/png/512/ios7-trash.png \
		ionicons-2.0.1/png/512/ios7-undo-outline.png \
		ionicons-2.0.1/png/512/ios7-undo.png \
		ionicons-2.0.1/png/512/ios7-unlocked-outline.png \
		ionicons-2.0.1/png/512/ios7-unlocked.png \
		ionicons-2.0.1/png/512/ios7-upload-outline.png \
		ionicons-2.0.1/png/512/ios7-upload.png \
		ionicons-2.0.1/png/512/ios7-videocam-outline.png \
		ionicons-2.0.1/png/512/ios7-videocam.png \
		ionicons-2.0.1/png/512/ios7-volume-high.png \
		ionicons-2.0.1/png/512/ios7-volume-low.png \
		ionicons-2.0.1/png/512/ios7-wineglass-outline.png \
		ionicons-2.0.1/png/512/ios7-wineglass.png \
		ionicons-2.0.1/png/512/ios7-world-outline.png \
		ionicons-2.0.1/png/512/ios7-world.png \
		ionicons-2.0.1/png/512/ipad.png \
		ionicons-2.0.1/png/512/iphone.png \
		ionicons-2.0.1/png/512/ipod.png \
		ionicons-2.0.1/png/512/jet.png \
		ionicons-2.0.1/png/512/key.png \
		ionicons-2.0.1/png/512/knife.png \
		ionicons-2.0.1/png/512/laptop.png \
		ionicons-2.0.1/png/512/leaf.png \
		ionicons-2.0.1/png/512/levels.png \
		ionicons-2.0.1/png/512/lightbulb.png \
		ionicons-2.0.1/png/512/link.png \
		ionicons-2.0.1/png/512/load-a.png \
		ionicons-2.0.1/png/512/load-b.png \
		ionicons-2.0.1/png/512/load-c.png \
		ionicons-2.0.1/png/512/load-d.png \
		ionicons-2.0.1/png/512/location.png \
		ionicons-2.0.1/png/512/locked.png \
		ionicons-2.0.1/png/512/log-in.png \
		ionicons-2.0.1/png/512/log-out.png \
		ionicons-2.0.1/png/512/loop.png \
		ionicons-2.0.1/png/512/magnet.png \
		ionicons-2.0.1/png/512/male.png \
		ionicons-2.0.1/png/512/man.png \
		ionicons-2.0.1/png/512/map.png \
		ionicons-2.0.1/png/512/medkit.png \
		ionicons-2.0.1/png/512/merge.png \
		ionicons-2.0.1/png/512/mic-a.png \
		ionicons-2.0.1/png/512/mic-b.png \
		ionicons-2.0.1/png/512/mic-c.png \
		ionicons-2.0.1/png/512/minus-circled.png \
		ionicons-2.0.1/png/512/minus-round.png \
		ionicons-2.0.1/png/512/minus.png \
		ionicons-2.0.1/png/512/model-s.png \
		ionicons-2.0.1/png/512/monitor.png \
		ionicons-2.0.1/png/512/more.png \
		ionicons-2.0.1/png/512/mouse.png \
		ionicons-2.0.1/png/512/music-note.png \
		ionicons-2.0.1/png/512/navicon-round.png \
		ionicons-2.0.1/png/512/navicon.png \
		ionicons-2.0.1/png/512/navigate.png \
		ionicons-2.0.1/png/512/network.png \
		ionicons-2.0.1/png/512/no-smoking.png \
		ionicons-2.0.1/png/512/nuclear.png \
		ionicons-2.0.1/png/512/outlet.png \
		ionicons-2.0.1/png/512/paper-airplane.png \
		ionicons-2.0.1/png/512/paperclip.png \
		ionicons-2.0.1/png/512/pause.png \
		ionicons-2.0.1/png/512/person-add.png \
		ionicons-2.0.1/png/512/person-stalker.png \
		ionicons-2.0.1/png/512/person.png \
		ionicons-2.0.1/png/512/pie-graph.png \
		ionicons-2.0.1/png/512/pin.png \
		ionicons-2.0.1/png/512/pinpoint.png \
		ionicons-2.0.1/png/512/pizza.png \
		ionicons-2.0.1/png/512/plane.png \
		ionicons-2.0.1/png/512/planet.png \
		ionicons-2.0.1/png/512/play.png \
		ionicons-2.0.1/png/512/playstation.png \
		ionicons-2.0.1/png/512/plus-circled.png \
		ionicons-2.0.1/png/512/plus-round.png \
		ionicons-2.0.1/png/512/plus.png \
		ionicons-2.0.1/png/512/podium.png \
		ionicons-2.0.1/png/512/pound.png \
		ionicons-2.0.1/png/512/power.png \
		ionicons-2.0.1/png/512/pricetag.png \
		ionicons-2.0.1/png/512/pricetags.png \
		ionicons-2.0.1/png/512/printer.png \
		ionicons-2.0.1/png/512/pull-request.png \
		ionicons-2.0.1/png/512/qr-scanner.png \
		ionicons-2.0.1/png/512/quote.png \
		ionicons-2.0.1/png/512/radio-waves.png \
		ionicons-2.0.1/png/512/record.png \
		ionicons-2.0.1/png/512/refresh.png \
		ionicons-2.0.1/png/512/reply-all.png \
		ionicons-2.0.1/png/512/reply.png \
		ionicons-2.0.1/png/512/ribbon-a.png \
		ionicons-2.0.1/png/512/ribbon-b.png \
		ionicons-2.0.1/png/512/sad.png \
		ionicons-2.0.1/png/512/scissors.png \
		ionicons-2.0.1/png/512/search.png \
		ionicons-2.0.1/png/512/settings.png \
		ionicons-2.0.1/png/512/share.png \
		ionicons-2.0.1/png/512/shuffle.png \
		ionicons-2.0.1/png/512/skip-backward.png \
		ionicons-2.0.1/png/512/skip-forward.png \
		ionicons-2.0.1/png/512/social-android-outline.png \
		ionicons-2.0.1/png/512/social-android.png \
		ionicons-2.0.1/png/512/social-apple-outline.png \
		ionicons-2.0.1/png/512/social-apple.png \
		ionicons-2.0.1/png/512/social-bitcoin-outline.png \
		ionicons-2.0.1/png/512/social-bitcoin.png \
		ionicons-2.0.1/png/512/social-buffer-outline.png \
		ionicons-2.0.1/png/512/social-buffer.png \
		ionicons-2.0.1/png/512/social-designernews-outline.png \
		ionicons-2.0.1/png/512/social-designernews.png \
		ionicons-2.0.1/png/512/social-dribbble-outline.png \
		ionicons-2.0.1/png/512/social-dribbble.png \
		ionicons-2.0.1/png/512/social-dropbox-outline.png \
		ionicons-2.0.1/png/512/social-dropbox.png \
		ionicons-2.0.1/png/512/social-facebook-outline.png \
		ionicons-2.0.1/png/512/social-facebook.png \
		ionicons-2.0.1/png/512/social-foursquare-outline.png \
		ionicons-2.0.1/png/512/social-foursquare.png \
		ionicons-2.0.1/png/512/social-freebsd-devil.png \
		ionicons-2.0.1/png/512/social-github-outline.png \
		ionicons-2.0.1/png/512/social-github.png \
		ionicons-2.0.1/png/512/social-google-outline.png \
		ionicons-2.0.1/png/512/social-google.png \
		ionicons-2.0.1/png/512/social-googleplus-outline.png \
		ionicons-2.0.1/png/512/social-googleplus.png \
		ionicons-2.0.1/png/512/social-hackernews-outline.png \
		ionicons-2.0.1/png/512/social-hackernews.png \
		ionicons-2.0.1/png/512/social-instagram-outline.png \
		ionicons-2.0.1/png/512/social-instagram.png \
		ionicons-2.0.1/png/512/social-linkedin-outline.png \
		ionicons-2.0.1/png/512/social-linkedin.png \
		ionicons-2.0.1/png/512/social-pinterest-outline.png \
		ionicons-2.0.1/png/512/social-pinterest.png \
		ionicons-2.0.1/png/512/social-reddit-outline.png \
		ionicons-2.0.1/png/512/social-reddit.png \
		ionicons-2.0.1/png/512/social-rss-outline.png \
		ionicons-2.0.1/png/512/social-rss.png \
		ionicons-2.0.1/png/512/social-skype-outline.png \
		ionicons-2.0.1/png/512/social-skype.png \
		ionicons-2.0.1/png/512/social-tumblr-outline.png \
		ionicons-2.0.1/png/512/social-tumblr.png \
		ionicons-2.0.1/png/512/social-tux.png \
		ionicons-2.0.1/png/512/social-twitter-outline.png \
		ionicons-2.0.1/png/512/social-twitter.png \
		ionicons-2.0.1/png/512/social-usd-outline.png \
		ionicons-2.0.1/png/512/social-usd.png \
		ionicons-2.0.1/png/512/social-vimeo-outline.png \
		ionicons-2.0.1/png/512/social-vimeo.png \
		ionicons-2.0.1/png/512/social-windows-outline.png \
		ionicons-2.0.1/png/512/social-windows.png \
		ionicons-2.0.1/png/512/social-wordpress-outline.png \
		ionicons-2.0.1/png/512/social-wordpress.png \
		ionicons-2.0.1/png/512/social-yahoo-outline.png \
		ionicons-2.0.1/png/512/social-yahoo.png \
		ionicons-2.0.1/png/512/social-youtube-outline.png \
		ionicons-2.0.1/png/512/social-youtube.png \
		ionicons-2.0.1/png/512/speakerphone.png \
		ionicons-2.0.1/png/512/speedometer.png \
		ionicons-2.0.1/png/512/spoon.png \
		ionicons-2.0.1/png/512/star.png \
		ionicons-2.0.1/png/512/stats-bars.png \
		ionicons-2.0.1/png/512/steam.png \
		ionicons-2.0.1/png/512/stop.png \
		ionicons-2.0.1/png/512/thermometer.png \
		ionicons-2.0.1/png/512/thumbsdown.png \
		ionicons-2.0.1/png/512/thumbsup.png \
		ionicons-2.0.1/png/512/toggle-filled.png \
		ionicons-2.0.1/png/512/toggle.png \
		ionicons-2.0.1/png/512/trash-a.png \
		ionicons-2.0.1/png/512/trash-b.png \
		ionicons-2.0.1/png/512/trophy.png \
		ionicons-2.0.1/png/512/umbrella.png \
		ionicons-2.0.1/png/512/university.png \
		ionicons-2.0.1/png/512/unlocked.png \
		ionicons-2.0.1/png/512/upload.png \
		ionicons-2.0.1/png/512/usb.png \
		ionicons-2.0.1/png/512/videocamera.png \
		ionicons-2.0.1/png/512/volume-high.png \
		ionicons-2.0.1/png/512/volume-low.png \
		ionicons-2.0.1/png/512/volume-medium.png \
		ionicons-2.0.1/png/512/volume-mute.png \
		ionicons-2.0.1/png/512/wand.png \
		ionicons-2.0.1/png/512/waterdrop.png \
		ionicons-2.0.1/png/512/wifi.png \
		ionicons-2.0.1/png/512/wineglass.png \
		ionicons-2.0.1/png/512/woman.png \
		ionicons-2.0.1/png/512/wrench.png \
		ionicons-2.0.1/png/512/xbox.png \
		../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gantt.pro mainwindow.h \
		ganttrect.h \
		ganttflow.h \
		constants.h \
		qtablewidgetnumberitem.h \
		gclgms.h \
		gdxcc.h \
		wizard.h \
		exportwizard.h \
		ganttgraphicsview.h \
		ganttline.h main.cpp \
		mainwindow.cpp \
		ganttrect.cpp \
		ganttflow.cpp \
		qtablewidgetnumberitem.cpp \
		gclgms.c \
		gdxcc.c \
		wizard.cpp \
		exportwizard.cpp \
		ganttgraphicsview.cpp \
		ganttline.cpp
QMAKE_TARGET  = Gantt
DESTDIR       = 
TARGET        = Gantt.app/Contents/MacOS/Gantt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_wizard.h ui_exportwizard.h $(OBJECTS)  
	@test -d Gantt.app/Contents/MacOS/ || mkdir -p Gantt.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gantt.pro ../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Gantt.pro \
		icons.qrc \
		../Qt/5.7/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Gantt.pro
../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Gantt.pro:
icons.qrc:
../Qt/5.7/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Gantt.pro

qmake_all: FORCE

Gantt.app/Contents/PkgInfo: 
	@test -d Gantt.app/Contents || mkdir -p Gantt.app/Contents
	@$(DEL_FILE) Gantt.app/Contents/PkgInfo
	@echo "APPL????" > Gantt.app/Contents/PkgInfo
Gantt.app/Contents/Resources/empty.lproj: 
	@test -d Gantt.app/Contents/Resources || mkdir -p Gantt.app/Contents/Resources
	@touch Gantt.app/Contents/Resources/empty.lproj
	
Gantt.app/Contents/Info.plist: 
	@test -d Gantt.app/Contents || mkdir -p Gantt.app/Contents
	@$(DEL_FILE) Gantt.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.coolius.Gantt,g" -e "s,@ICON@,icon.icns,g" -e "s,@EXECUTABLE@,Gantt,g" -e "s,@LIBRARY@,Gantt,g" -e "s,@TYPEINFO@,????,g" ../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Gantt.app/Contents/Info.plist
Gantt.app/Contents/Resources/icon.icns: icon.icns
	@test -d Gantt.app/Contents/Resources/ || mkdir -p Gantt.app/Contents/Resources/
	@$(DEL_FILE) Gantt.app/Contents/Resources/icon.icns
	@$(COPY_FILE) icon.icns Gantt.app/Contents/Resources/icon.icns

all: Makefile \
		Gantt.app/Contents/PkgInfo \
		Gantt.app/Contents/Resources/empty.lproj \
		Gantt.app/Contents/Info.plist \
		Gantt.app/Contents/Resources/icon.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h ganttrect.h ganttflow.h constants.h qtablewidgetnumberitem.h gclgms.h gdxcc.h wizard.h exportwizard.h ganttgraphicsview.h ganttline.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp ganttrect.cpp ganttflow.cpp qtablewidgetnumberitem.cpp gclgms.c gdxcc.c wizard.cpp exportwizard.cpp ganttgraphicsview.cpp ganttline.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui wizard.ui exportwizard.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Gantt.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		../Qt/5.7/clang_64/bin/rcc \
		ionicons-2.0.1/png/512/minus-round.png \
		ionicons-2.0.1/png/512/navicon-round.png \
		ionicons-2.0.1/png/512/plus-round.png \
		ionicons-2.0.1/png/512/arrow-expand.png
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_ganttrect.cpp moc_ganttflow.cpp moc_wizard.cpp moc_exportwizard.cpp moc_ganttline.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_ganttrect.cpp moc_ganttflow.cpp moc_wizard.cpp moc_exportwizard.cpp moc_ganttline.cpp
moc_mainwindow.cpp: ../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		mainwindow.h \
		exportwizard.h \
		mainwindow.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_ganttrect.cpp: ../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib ganttrect.h -o moc_ganttrect.cpp

moc_ganttflow.cpp: ../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttflow.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib ganttflow.h -o moc_ganttflow.cpp

moc_wizard.cpp: ../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		exportwizard.h \
		wizard.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib wizard.h -o moc_wizard.cpp

moc_exportwizard.cpp: ../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		exportwizard.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib exportwizard.h -o moc_exportwizard.cpp

moc_ganttline.cpp: ../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttline.h \
		../Qt/5.7/clang_64/bin/moc
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/juliusnaeumann/Developer/Gantt -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++ -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/i686-w64-mingw32.static -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include/c++/backward -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include -I/Users/juliusnaeumann/Developer/mxe/usr/lib/gcc/i686-w64-mingw32.static/4.9.4/include-fixed -I/Users/juliusnaeumann/Developer/mxe/usr/i686-w64-mingw32.static/include -F/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/lib ganttline.h -o moc_ganttline.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_wizard.h ui_exportwizard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_wizard.h ui_exportwizard.h
ui_mainwindow.h: mainwindow.ui \
		../Qt/5.7/clang_64/bin/uic
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_wizard.h: wizard.ui \
		../Qt/5.7/clang_64/bin/uic
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/uic wizard.ui -o ui_wizard.h

ui_exportwizard.h: exportwizard.ui \
		../Qt/5.7/clang_64/bin/uic
	/Users/juliusnaeumann/Developer/Qt/5.7/clang_64/bin/uic exportwizard.ui -o ui_exportwizard.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		exportwizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		exportwizard.h \
		ui_mainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QtMath \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QToolTip \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtooltip.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		constants.h \
		qtablewidgetnumberitem.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h \
		../Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers/QPrinter \
		../Qt/5.7/clang_64/lib/QtPrintSupport.framework/Headers/qprinter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

ganttrect.o: ganttrect.cpp ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		constants.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QtGui \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QVariantAnimation \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qvariantanimation.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttrect.o ganttrect.cpp

ganttflow.o: ganttflow.cpp ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttflow.o ganttflow.cpp

qtablewidgetnumberitem.o: qtablewidgetnumberitem.cpp qtablewidgetnumberitem.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QTableWidgetItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qtablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtablewidgetnumberitem.o qtablewidgetnumberitem.cpp

gclgms.o: gclgms.c gclgms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gclgms.o gclgms.c

gdxcc.o: gdxcc.c gdxcc.h \
		gclgms.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gdxcc.o gdxcc.c

wizard.o: wizard.cpp wizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		mainwindow.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QMap \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QActionGroup \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qactiongroup.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		exportwizard.h \
		ui_wizard.h \
		gclgms.h \
		gdxcc.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wizard.o wizard.cpp

exportwizard.o: exportwizard.cpp exportwizard.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWizard \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwizard.h \
		ui_exportwizard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportwizard.o exportwizard.cpp

ganttgraphicsview.o: ganttgraphicsview.cpp ganttgraphicsview.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		ganttrect.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		ganttflow.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsPolygonItem \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QtGui \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrgba64.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qtguiversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttgraphicsview.o ganttgraphicsview.cpp

ganttline.o: ganttline.cpp ganttline.h \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QObject \
		../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGraphicsLineItem \
		../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPen \
		../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ganttline.o ganttline.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_ganttrect.o: moc_ganttrect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganttrect.o moc_ganttrect.cpp

moc_ganttflow.o: moc_ganttflow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganttflow.o moc_ganttflow.cpp

moc_wizard.o: moc_wizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wizard.o moc_wizard.cpp

moc_exportwizard.o: moc_exportwizard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportwizard.o moc_exportwizard.cpp

moc_ganttline.o: moc_ganttline.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ganttline.o moc_ganttline.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

